### PR TITLE
Updated variables

### PR DESCRIPTION
**Pull request by ganesh-katakam-T18451**

### CODE REVIEW

**Comment by ganesh-katakam-T18451** [comment]
**Plan Error**
```
GET https://api.github.com/repos/ganesh-katakam-T18451/test-atlantis/pulls/6/files?per_page=300: 404 Not Found []
```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Hello world

Completed 100 Bytes/100 Bytes (992 Bytes/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars

aws_instance.test-atlantis: Refreshing state... [id=i-08887af97f10e5574]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be updated in-place
~ resource "aws_instance" "test-atlantis" {
        id                                   = "i-08887af97f10e5574"
      ~ tags                                 = {
          + "Owner" = "ganesh.katakam@freshworks.com"
          ~ "Type"  = "test-tfvars-tag" -> "Development"
            # (1 unchanged element hidden)
        }
      ~ tags_all                             = {
          + "Owner" = "ganesh.katakam@freshworks.com"
          ~ "Type"  = "test-tfvars-tag" -> "Development"
            # (1 unchanged element hidden)
        }
        # (27 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Hello world

Completed 100 Bytes/100 Bytes (850 Bytes/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars

aws_instance.test-atlantis: Refreshing state... [id=i-08887af97f10e5574]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be updated in-place
~ resource "aws_instance" "test-atlantis" {
        id                                   = "i-08887af97f10e5574"
      ~ instance_type                        = "c5.large" -> "c4.large"
      ~ tags                                 = {
          + "Owner" = "ganesh.katakam@freshworks.com"
          ~ "Type"  = "test-tfvars-tag" -> "Development"
            # (1 unchanged element hidden)
        }
      ~ tags_all                             = {
          + "Owner" = "ganesh.katakam@freshworks.com"
          ~ "Type"  = "test-tfvars-tag" -> "Development"
            # (1 unchanged element hidden)
        }
        # (26 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by Adharsh-Muraleedharan — APPROVED** [review]

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Performing Terraform apply

aws_instance.test-atlantis: Modifying... [id=i-08887af97f10e5574]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 10s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 20s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 30s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 40s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 50s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m0s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m10s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m20s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m30s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m40s elapsed]
aws_instance.test-atlantis: Still modifying... [id=i-08887af97f10e5574, 1m50s elapsed]
aws_instance.test-atlantis: Modifications complete after 1m54s [id=i-08887af97f10e5574]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

ec2_instanceId = "i-08887af97f10e5574"

```
</details>

**Comment by ganesh-katakam-T18451** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
