### PR TITLE
Added assume role

### PR DESCRIPTION
**Pull request by ganesh-katakam-T18451**

### CODE REVIEW

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (2.5 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Error: Variables not allowed

  on main.tf line 20, in terraform:
  20:     region = "${var.provider_region}"

Variables may not be used here.


```
</details>

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (1.9 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
	status code: 400, request id: 8K9CH7H17Y42W53W, host id: J1P/at6hTfJL/m1U7F7FT9fRoG5kBdO3wNAub+aUVMbQpv++ypocAXu9OBSOhxRo++WuvC0C2bM=

```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (1.7 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Error: "region": required field is not set



```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (2.0 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: TMBBYEAGB47XN6BE, host id: eeUMY2ikw0Hhg5QIlzMNyKo6AGEfXRKWpJm//doIFDzPdC/xpH72k5Qnh/TOzK191lRhkfjOcZs=

```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (1.6 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Error: error configuring S3 Backend: IAM Role (some-role) cannot be assumed.

There are a number of possible causes of this - the most common are:
  * The credentials used in order to assume the role are invalid
  * The credentials do not have appropriate permission to assume the role
  * The role ARN is not valid

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors




```
</details>

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Hello world

Completed 207 Bytes/207 Bytes (1.4 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars


Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: 8THWVY7QWXJ56KSA, host id: k9usuNjdAATAbcK342RcnCpyXlsViAeziK7DB5P5eCnxj76oBHC1JDUX8WvI/j7xNvGaoW+cldw=

```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Starting setup
Completed 207 Bytes/207 Bytes (1.7 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
# Default provider representing destination account
provider "aws" {
  region = "${var.provider_region}"
  assume_role {
    role_arn     = "${var.role_arn}"
    session_name = "test-atlantis"
  }
}

#Provider representing atlantis server account
provider "aws" {
  alias  = "atlantis"
  region    = "${var.provider_region}"
}

terraform {
  backend "s3" {
    bucket = "fcp-staging-customer"
    key    = "test-atlantis/terraform.tfstate"
    region = "us-east-1"
    role_arn = "arn:aws:iam::910176200576:role/fcp-staging-customer-assume-role"
  }
}

resource "aws_instance" "test-atlantis" {
  ami           = "ami-092e83e9512cf43d8"
  instance_type = "c4.large"

  tags = {
    Name = var.instance_name,
    Type = var.type_name,
    Owner = var.owner_name
  }
}Finished setup


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be created
+ resource "aws_instance" "test-atlantis" {
      + ami                                  = "ami-092e83e9512cf43d8"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "c4.large"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tags_all                             = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ ec2_instanceId = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Starting setup
Completed 207 Bytes/207 Bytes (2.0 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
# Default provider representing destination account
provider "aws" {
  region = "${var.provider_region}"
  assume_role {
    role_arn     = "${var.role_arn}"
    session_name = "test-atlantis"
  }
}

#Provider representing atlantis server account
provider "aws" {
  alias  = "atlantis"
  region    = "${var.provider_region}"
}

terraform {
  backend "s3" {
    bucket = "fcp-staging-customer"
    key    = "test-atlantis/terraform.tfstate"
    region = "us-east-1"
    role_arn = "arn:aws:iam::910176200576:role/fcp-staging-customer-assume-role"
  }
}

resource "aws_instance" "test-atlantis" {
  ami           = "ami-087c17d1fe0178315"
  instance_type = "c5.large"

  tags = {
    Name = var.instance_name,
    Type = var.type_name,
    Owner = var.owner_name
  }
}Finished setup


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be created
+ resource "aws_instance" "test-atlantis" {
      + ami                                  = "ami-087c17d1fe0178315"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "c5.large"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tags_all                             = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ ec2_instanceId = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by Adharsh-Muraleedharan — APPROVED** [review]

**Comment by Adharsh-Muraleedharan** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default/test-atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Performing Terraform apply

aws_instance.test-atlantis: Creating...

Error: Error launching source instance: MissingInput: No subnets found for the default VPC 'vpc-9bd6a7e1'. Please specify a subnet.
	status code: 400, request id: 8f5a1073-9c92-4f59-929e-f2f7863eeb79

  with aws_instance.test-atlantis,
  on main.tf line 25, in resource "aws_instance" "test-atlantis":
  25: resource "aws_instance" "test-atlantis" {


```

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default/test-atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Performing Terraform apply

aws_instance.test-atlantis: Creating...

Error: Error launching source instance: MissingInput: No subnets found for the default VPC 'vpc-9bd6a7e1'. Please specify a subnet.
	status code: 400, request id: e2d7e79e-2dd6-4540-938c-7a29e8e08a77

  with aws_instance.test-atlantis,
  on main.tf line 25, in resource "aws_instance" "test-atlantis":
  25: resource "aws_instance" "test-atlantis" {


```

**Comment by ganesh-katakam-T18451** [comment]
terraform plan

**Comment by ganesh-katakam-T18451** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Starting setup
Completed 207 Bytes/207 Bytes (1.9 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
# Default provider representing destination account
provider "aws" {
  region = "${var.provider_region}"
  assume_role {
    role_arn     = "${var.role_arn}"
    session_name = "test-atlantis"
  }
}

#Provider representing atlantis server account
provider "aws" {
  alias  = "atlantis"
  region    = "${var.provider_region}"
}

terraform {
  backend "s3" {
    bucket = "fcp-staging-customer"
    key    = "test-atlantis/terraform.tfstate"
    region = "us-east-1"
    role_arn = "arn:aws:iam::910176200576:role/fcp-staging-customer-assume-role"
  }
}

resource "aws_instance" "test-atlantis" {
  ami           = "ami-087c17d1fe0178315"
  instance_type = "c5.large"

  tags = {
    Name = var.instance_name,
    Type = var.type_name,
    Owner = var.owner_name
  }
}Finished setup


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be created
+ resource "aws_instance" "test-atlantis" {
      + ami                                  = "ami-087c17d1fe0178315"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "c5.large"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tags_all                             = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ ec2_instanceId = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default/test-atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/7/default": exit status 1
Performing Terraform apply

aws_instance.test-atlantis: Creating...

Error: Error launching source instance: MissingInput: No subnets found for the default VPC 'vpc-9bd6a7e1'. Please specify a subnet.
	status code: 400, request id: 9191d444-38b7-49cc-9ded-3f030cd2c506

  with aws_instance.test-atlantis,
  on main.tf line 25, in resource "aws_instance" "test-atlantis":
  25: resource "aws_instance" "test-atlantis" {


```

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for project: `test-atlantis` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Starting setup
Completed 207 Bytes/207 Bytes (1.9 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
# Default provider representing destination account
provider "aws" {
  region = "${var.provider_region}"
  assume_role {
    role_arn     = "${var.role_arn}"
    session_name = "test-atlantis"
  }
}

#Provider representing atlantis server account
provider "aws" {
  alias  = "atlantis"
  region    = "${var.provider_region}"
}

terraform {
  backend "s3" {
    bucket = "fcp-staging-customer"
    key    = "test-atlantis/terraform.tfstate"
    region = "us-east-1"
    role_arn = "arn:aws:iam::910176200576:role/fcp-staging-customer-assume-role"
  }
}

resource "aws_instance" "test-atlantis" {
  ami           = "ami-087c17d1fe0178315"
  instance_type = "c5.large"
  subnet_id = "subnet-0179cd952bf0953ad"

  tags = {
    Name = var.instance_name,
    Type = var.type_name,
    Owner = var.owner_name
  }
}Finished setup


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.test-atlantis will be created
+ resource "aws_instance" "test-atlantis" {
      + ami                                  = "ami-087c17d1fe0178315"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "c5.large"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = "subnet-0179cd952bf0953ad"
      + tags                                 = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tags_all                             = {
          + "Name"  = "test-tfvars"
          + "Owner" = "ganesh.katakam@freshworks.com"
          + "Type"  = "Development"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ ec2_instanceId = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test-atlantis`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis-79dfb6dbd6-sfq49:4141/lock?id=ganesh-katakam-T18451%252Ftest-atlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test-atlantis`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

```diff
Performing Terraform apply

aws_instance.test-atlantis: Creating...
aws_instance.test-atlantis: Still creating... [10s elapsed]
aws_instance.test-atlantis: Creation complete after 13s [id=i-073475bdc355cb8e5]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

ec2_instanceId = "i-073475bdc355cb8e5"

```

**Comment by ganesh-katakam-T18451** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
