### PR TITLE
New code changes

### PR DESCRIPTION
**Pull request by ganesh-katakam-T18451**

### CODE REVIEW

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `test`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/9/test": exit status 1
Starting setup
Completed 207 Bytes/207 Bytes (2.1 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
Finished setup


Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

The currently selected workspace (test) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. default

  Enter a value: 
Error: Failed to select workspace: EOF



```
</details>

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/9/default/test-atlantis-default.tfplan\" -var-file common.tfvars" in "/home/atlantis/.atlantis/repos/ganesh-katakam-T18451/test-atlantis/9/default": exit status 1
Starting setup
Completed 207 Bytes/207 Bytes (2.2 KiB/s) with 1 file(s) remaining
download: s3://fcp-frontend/atlantis/common.tfvars to ./common.tfvars
Finished setup


Error: No value for required variable

  on variables.tf line 21:
  21: variable "backend_region" {

The root module input variable "backend_region" is not set, and has no
default value. Use a -var or -var-file command line argument to provide a
value for this variable.

Error: No value for required variable

  on variables.tf line 31:
  31: variable "subnet_id" {

The root module input variable "subnet_id" is not set, and has no default
value. Use a -var or -var-file command line argument to provide a value for
this variable.

```
</details>

**Comment by ganesh-katakam-T18451** [comment]
atlantis plan

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply -p test-atlantis

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by Adharsh-Muraleedharan — APPROVED** [review]

**Comment by ganesh-katakam-T18451** [comment]
atlantis apply

**Comment by ganesh-katakam-T18451** [comment]
Ran Apply for project: `test-atlantis` dir: `.` workspace: `default`

```diff
Performing Terraform apply

aws_instance.test-atlantis: Creating...
aws_instance.test-atlantis: Still creating... [10s elapsed]
aws_instance.test-atlantis: Creation complete after 14s [id=i-0f834a2f9ec48911d]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

ec2_instanceId = "i-0f834a2f9ec48911d"

```

**Comment by ganesh-katakam-T18451** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
